### ISSUE TITLE
Random Crash when closing the engine (Debug)

### ISSUE THREAD

**Issue by AitorSimona** [Broken-Gem-Studio/Broken-Engine#37] opened 2020-03-06 13:25 UTC
## Bug Description
Abort/Exception called on closing the engine, no idea on how to reproduce this, see screenshot. Could not reproduce in Release compilation

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [X] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [X] Crash 
- [ ] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Just run and close the engine, at some point it will happen 
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [ ] Very Often
* [ ] Usually
* [X] Few Times
* [ ] Few Times under specific conditions

### Expected result:
No crash...

### Actual result:
Crash

## Screenshots and Illustrations:
![image](https://user-images.githubusercontent.com/36265599/76086748-053fad80-5fb5-11ea-811b-d54b7bc6e95a.png)

## Build
- **Please specify the build:** ``Insert the build here``
latest commit 943 Release branch

## Observations and Additional Information
If we forget about all these debug errors we may reach a point where we won't be able to debug properly...

**Comment by Scarzard** [comment] 2020-03-07 22:01
Tested. After a 6/7 times of playing around with the engine and closing it, it happened again. 

Very low reproducibility rate. Will be hard to pin-point the origin causing the problem

**Comment by t3m1X** [comment] 2020-03-08 17:10
Can now replicate consistently, issue seems to be with deallocating json objects on exiting Application.

**Comment by t3m1X** [comment] 2020-03-11 11:33
Fixed at pull #54

**Closed as completed by t3m1X** 2020-03-11 11:33 UTC
Labels: Bug, Medium Priority
