### ISSUE TITLE
Objects can't be unparented

### ISSUE THREAD

**Issue by lucho1** [Broken-Gem-Studio/Broken-Engine#312] opened 2020-05-02 17:35 UTC
## Bug Description
Thought it was fixed, but the GameObjects cannot be unparented. If, in hierarchy, they are dragged into an empty space, they should be unparented.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [x] Game Objects
* [x] UI/UX 
* [ ] Scripting
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Create a couple of objects
 
 2. Make some parents between them
 
 3. Observe they cannot be "unparented"

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [x] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
If, in hierarchy, they are dragged into an empty space, they should be unparented.

### Actual result:
They can't be unparented

## Build
- **Please specify the build:** ``Insert the build here``
v0.5.x

**Comment by AitorSimona** [comment] 2020-05-04 16:29
Could not reproduce, I keep dragging objects out without problem, if it does not happen again in alpha 2 I will close this

**Comment by lucho1** [comment] 2020-05-04 17:17
![GIF](https://user-images.githubusercontent.com/11302677/80993736-e1290d00-8e3b-11ea-9a41-809f1cb84fbe.gif)

**Comment by AitorSimona** [comment] 2020-05-04 17:28
@lucho1 Try selecting the element you want to take out first :)

**Comment by lucho1** [comment] 2020-05-04 18:19
amazing discoverooo

**Comment by lucho1** [comment] 2020-05-04 18:19
Didn't remembered that Oscar told us this thing when implementing it :(

**Comment by lucho1** [comment] 2020-05-04 18:20
Then, if all OK, I think we can close this

**Closed as completed** 2020-05-04 22:13 UTC
Labels: Enhancement, Medium Priority
