### ISSUE TITLE
Save & Load of "Play" not working as intended

### ISSUE THREAD

**Issue by ch0m5** [Broken-Gem-Studio/Broken-Engine#46] opened 2020-03-10 17:21 UTC
## Bug Description
Currently, when you press STOP the changes made before pressing PLAY aren't correctly saved. It seems that STOP reloads the currently saved Scene, and that's not how it's expected to work.

There are 2 type of Scenes:
1. **Saved Scene**: This scene is saved and loaded per user request, and ONLY per user request.
2. **Temporal Scene**: This scene is a copy of the scene state right before pressing PLAY, and is overwritten every time PLAY is pressed, and loaded every time STOP is pressed.

At the moment, pressing STOP seems to load the Saved Scene, not the Temporal Scene, and the designer expects to find the Scene right as he left it.

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ ] Audio 
* [ ] Particles
* [x] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Save a Scene with GO and components in them.
 
 2. Make new changes, like adding components or moving GOs.
 
 3. PLAY and STOP.

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Scene reloads and is right as I left it before pressing PLAY.

### Actual result:
The Scene is reloaded back to the changes it had when I manually saved the scene.

## Build
BrokenEngine 2.0

**Comment by t3m1X** [comment] 2020-03-10 18:38
Duplicate of #42

**Closed as completed by t3m1X** 2020-03-10 18:38 UTC
Labels: Bug, Duplicate, Medium Priority

**Comment by AitorSimona** [comment] 2020-03-10 18:52
Bug introduced in a previous merge, now solved
